# Generated by Django 5.0.2 on 2024-03-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naval_battle', '0002_map_match_matchplayer_ship'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='qwerty123', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='user_asd', max_length=20),
        ),
    ]
