# Generated by Django 5.0.2 on 2024-03-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naval_battle', '0003_userprofile_password_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('DEFAULT', 'DEFAULT')], default='DEFAULT', max_length=20),
        ),
    ]
